### ISSUE TITLE
Planung

### ISSUE THREAD

**Issue by FaGru3n** [FaGru3n/workshop#8]

**Comment by wmisag** [comment]
Gute Frage! :)

**Comment by PhillipNalesny** [comment]
@FaGru3n --> gibt es eine Agile Hive Alternative in gitHub?

**Comment by FaGru3n** [comment]
Nicht in dem selben Umfang kann aber nachgestellt werden in ähnlichem Umfang...  👍🏼 
https://docs.github.com/en/issues/guides

**Comment by FaGru3n** [comment]
> @FaGru3n --> gibt es eine Agile Hive Alternative in gitHub?

da es nach dem Consortia benötigen wir kostenfreie Produkte daher wurde nach kostenfreien best pratices gesucht und gemeinsam für GitHub entschieden... ansonsten gern noch mal auf Daniel oder Björn zugehen.
